import { Financial } from './financial';
import { Building } from './building';
import { Constants, ThermalTechno } from './io';
declare class Thermic {
    readonly constants: Constants;
    householdPerson: number;
    literByPersonByDay: number;
    hotWaterProducer: ThermalTechno;
    cost: number;
    annualMaintenanceCost: number;
    maintenanceRate: number;
    grant: number;
    VATrate: number;
    literByDay: number;
    producerYield: number;
    netDemand: number;
    hotWaterEnergyCost: number;
    hotWaterEnergyCostIndex: number;
    solarProduction: number;
    pumpConsumption: number;
    building: Building;
    constructor(constants: Constants, the_household_person: number, the_liter_by_person_by_day: number, the_liter_by_day: number, the_hot_water_producer: ThermalTechno, the_cost: number, the_annual_maintenance_cost: number, the_maintenance_rate: number, the_grant: number, the_VAT_rate: number);
    computeCost(): number;
    computeAnnualMaintenanceCost(): number;
    computeLiterByDay(): number;
    computeProducerYield(): number;
    computeNetDemand(): number;
    computeHotWaterEnergyCost(): number;
    computeHotWaterEnergyCostIndex(): number;
    computeSolarProduction(): number;
    computePumpConsumption(): number;
}
declare const getAzimuthBestRoof: (constants: import("io-ts").TypeOfProps<{
    max_power: import("io-ts").NumberType;
    co2_emissions_by_kwh: import("io-ts").NumberType;
    meter_cost: import("io-ts").NumberType;
    onduleur_cost_factor: import("io-ts").NumberType;
    onduleur_replacement_rate: import("io-ts").NumberType;
    redevance_cost: import("io-ts").NumberType;
    pvheater_cost: import("io-ts").NumberType;
    battery_cost: import("io-ts").NumberType;
    inflation_rate: import("io-ts").NumberType;
    elec_buying_price: import("io-ts").NumberType;
    elec_index: import("io-ts").NumberType;
    discount_rate: import("io-ts").NumberType;
    cv_rate_switch_power: import("io-ts").NumberType;
    cv_rate_low_power: import("io-ts").NumberType;
    cv_rate_high_power: import("io-ts").NumberType;
    cv_time: import("io-ts").NumberType;
    cv_end_of_compensation_year: import("io-ts").NumberType;
    production_yearly_loss_index: import("io-ts").NumberType;
    maintenance_cost_factor: import("io-ts").NumberType;
    max_solar_productivity: import("io-ts").NumberType;
    medium_solar_productivity: import("io-ts").NumberType;
    max_solar_irradiance: import("io-ts").NumberType;
    flat_roof_tilt: import("io-ts").NumberType;
    low_productivity_limit: import("io-ts").NumberType;
    energy_sobriety_factor: import("io-ts").NumberType;
    electric_water_heater_factor: import("io-ts").NumberType;
    electric_water_heater_min_consumption: import("io-ts").NumberType;
    electric_heating_factor: import("io-ts").NumberType;
    thermic_installation_cost: import("io-ts").NumberType;
    thermic_maintenance_cost: import("io-ts").NumberType;
    max_liter_per_day: import("io-ts").NumberType;
    min_thermic_area: import("io-ts").NumberType;
    obstacle_default_rate: import("io-ts").NumberType;
    obstacle: import("io-ts").InterfaceType<{
        velux: import("io-ts").NumberType;
        dormerWindow: import("io-ts").NumberType;
        flatRoofWindow: import("io-ts").NumberType;
        chimneySmoke: import("io-ts").NumberType;
        terraceInUse: import("io-ts").NumberType;
        lift: import("io-ts").NumberType;
        existingSolarPannel: import("io-ts").NumberType;
    }, import("io-ts").TypeOfProps<{
        velux: import("io-ts").NumberType;
        dormerWindow: import("io-ts").NumberType;
        flatRoofWindow: import("io-ts").NumberType;
        chimneySmoke: import("io-ts").NumberType;
        terraceInUse: import("io-ts").NumberType;
        lift: import("io-ts").NumberType;
        existingSolarPannel: import("io-ts").NumberType;
    }>, import("io-ts").OutputOfProps<{
        velux: import("io-ts").NumberType;
        dormerWindow: import("io-ts").NumberType;
        flatRoofWindow: import("io-ts").NumberType;
        chimneySmoke: import("io-ts").NumberType;
        terraceInUse: import("io-ts").NumberType;
        lift: import("io-ts").NumberType;
        existingSolarPannel: import("io-ts").NumberType;
    }>, import("io-ts").mixed>;
    lost_space_rate: import("io-ts").NumberType;
    energetic_cost_factor: import("io-ts").InterfaceType<{
        Belgium: import("io-ts").NumberType;
        Europe: import("io-ts").NumberType;
        China: import("io-ts").NumberType;
    }, import("io-ts").TypeOfProps<{
        Belgium: import("io-ts").NumberType;
        Europe: import("io-ts").NumberType;
        China: import("io-ts").NumberType;
    }>, import("io-ts").OutputOfProps<{
        Belgium: import("io-ts").NumberType;
        Europe: import("io-ts").NumberType;
        China: import("io-ts").NumberType;
    }>, import("io-ts").mixed>;
    breakdown_cost_factor: import("io-ts").InterfaceType<{
        Belgium: import("io-ts").InterfaceType<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        Europe: import("io-ts").InterfaceType<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        China: import("io-ts").InterfaceType<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
    }, import("io-ts").TypeOfProps<{
        Belgium: import("io-ts").InterfaceType<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        Europe: import("io-ts").InterfaceType<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        China: import("io-ts").InterfaceType<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
    }>, import("io-ts").OutputOfProps<{
        Belgium: import("io-ts").InterfaceType<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        Europe: import("io-ts").InterfaceType<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        China: import("io-ts").InterfaceType<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            panels: import("io-ts").NumberType;
            setup: import("io-ts").NumberType;
            inverter: import("io-ts").NumberType;
            transportBE: import("io-ts").NumberType;
            transportEU: import("io-ts").NumberType;
            transportBoat: import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
    }>, import("io-ts").mixed>;
    pv_yield: import("io-ts").InterfaceType<{
        poly: import("io-ts").NumberType;
        mono: import("io-ts").NumberType;
        mono_high: import("io-ts").NumberType;
    }, import("io-ts").TypeOfProps<{
        poly: import("io-ts").NumberType;
        mono: import("io-ts").NumberType;
        mono_high: import("io-ts").NumberType;
    }>, import("io-ts").OutputOfProps<{
        poly: import("io-ts").NumberType;
        mono: import("io-ts").NumberType;
        mono_high: import("io-ts").NumberType;
    }>, import("io-ts").mixed>;
    pv_cost: import("io-ts").InterfaceType<{
        poly: import("io-ts").NumberType;
        mono: import("io-ts").NumberType;
        mono_high: import("io-ts").NumberType;
    }, import("io-ts").TypeOfProps<{
        poly: import("io-ts").NumberType;
        mono: import("io-ts").NumberType;
        mono_high: import("io-ts").NumberType;
    }>, import("io-ts").OutputOfProps<{
        poly: import("io-ts").NumberType;
        mono: import("io-ts").NumberType;
        mono_high: import("io-ts").NumberType;
    }>, import("io-ts").mixed>;
    self_production: import("io-ts").InterfaceType<{
        default: import("io-ts").InterfaceType<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        energySobriety: import("io-ts").InterfaceType<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        chargeShift: import("io-ts").InterfaceType<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        pvHeater: import("io-ts").InterfaceType<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        battery: import("io-ts").InterfaceType<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
    }, import("io-ts").TypeOfProps<{
        default: import("io-ts").InterfaceType<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        energySobriety: import("io-ts").InterfaceType<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        chargeShift: import("io-ts").InterfaceType<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        pvHeater: import("io-ts").InterfaceType<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        battery: import("io-ts").InterfaceType<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
    }>, import("io-ts").OutputOfProps<{
        default: import("io-ts").InterfaceType<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        energySobriety: import("io-ts").InterfaceType<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        chargeShift: import("io-ts").InterfaceType<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        pvHeater: import("io-ts").InterfaceType<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        battery: import("io-ts").InterfaceType<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "0.6": import("io-ts").NumberType;
            "1": import("io-ts").NumberType;
            "1.4": import("io-ts").NumberType;
            "1.8": import("io-ts").NumberType;
            "2.2": import("io-ts").NumberType;
            "2.6": import("io-ts").NumberType;
            "3": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
    }>, import("io-ts").mixed>;
    hot_water_producer_yield: import("io-ts").InterfaceType<{
        gas: import("io-ts").NumberType;
        fuel: import("io-ts").NumberType;
        electric: import("io-ts").NumberType;
    }, import("io-ts").TypeOfProps<{
        gas: import("io-ts").NumberType;
        fuel: import("io-ts").NumberType;
        electric: import("io-ts").NumberType;
    }>, import("io-ts").OutputOfProps<{
        gas: import("io-ts").NumberType;
        fuel: import("io-ts").NumberType;
        electric: import("io-ts").NumberType;
    }>, import("io-ts").mixed>;
    hot_water_energy_cost: import("io-ts").InterfaceType<{
        gas: import("io-ts").NumberType;
        fuel: import("io-ts").NumberType;
        electric: import("io-ts").NumberType;
    }, import("io-ts").TypeOfProps<{
        gas: import("io-ts").NumberType;
        fuel: import("io-ts").NumberType;
        electric: import("io-ts").NumberType;
    }>, import("io-ts").OutputOfProps<{
        gas: import("io-ts").NumberType;
        fuel: import("io-ts").NumberType;
        electric: import("io-ts").NumberType;
    }>, import("io-ts").mixed>;
    hot_water_energy_cost_index: import("io-ts").InterfaceType<{
        gas: import("io-ts").NumberType;
        fuel: import("io-ts").NumberType;
        electric: import("io-ts").NumberType;
    }, import("io-ts").TypeOfProps<{
        gas: import("io-ts").NumberType;
        fuel: import("io-ts").NumberType;
        electric: import("io-ts").NumberType;
    }>, import("io-ts").OutputOfProps<{
        gas: import("io-ts").NumberType;
        fuel: import("io-ts").NumberType;
        electric: import("io-ts").NumberType;
    }>, import("io-ts").mixed>;
    co2_emissions_by_kwh_thermic: import("io-ts").InterfaceType<{
        gas: import("io-ts").NumberType;
        fuel: import("io-ts").NumberType;
        electric: import("io-ts").NumberType;
    }, import("io-ts").TypeOfProps<{
        gas: import("io-ts").NumberType;
        fuel: import("io-ts").NumberType;
        electric: import("io-ts").NumberType;
    }>, import("io-ts").OutputOfProps<{
        gas: import("io-ts").NumberType;
        fuel: import("io-ts").NumberType;
        electric: import("io-ts").NumberType;
    }>, import("io-ts").mixed>;
    thermic_production: import("io-ts").InterfaceType<{
        "60": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        "90": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        "120": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        "150": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        "180": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        "210": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
    }, import("io-ts").TypeOfProps<{
        "60": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        "90": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        "120": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        "150": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        "180": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        "210": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
    }>, import("io-ts").OutputOfProps<{
        "60": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        "90": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        "120": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        "150": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        "180": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
        "210": import("io-ts").InterfaceType<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }, import("io-ts").TypeOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").OutputOfProps<{
            "90": import("io-ts").NumberType;
            '112.5': import("io-ts").NumberType;
            "135": import("io-ts").NumberType;
            "157.5": import("io-ts").NumberType;
            "180": import("io-ts").NumberType;
            "202.5": import("io-ts").NumberType;
            "225": import("io-ts").NumberType;
            "247.5": import("io-ts").NumberType;
            "270": import("io-ts").NumberType;
        }>, import("io-ts").mixed>;
    }>, import("io-ts").mixed>;
}>, b: Building) => number;
interface Balances {
    [key: string]: number[];
}
declare const computeBalances: (t: Thermic, fin: Financial, nYears: number) => Balances;
declare const computeThermicGain: (t: Thermic, nYears: number) => number;
declare const computeThermicEnvironmentalGain: (t: Thermic, nYears: number) => number;
declare const computeActualReturnTimeThermic: (t: Thermic, fin: Financial, nYears: number) => number;
interface productionPrices {
    [key: string]: number;
}
declare const computeProductionPrices: (t: Thermic, nYears: number) => productionPrices;
export { Thermic, getAzimuthBestRoof, computeBalances, computeThermicGain, computeThermicEnvironmentalGain, computeActualReturnTimeThermic, computeProductionPrices };
